### ISSUE TITLE
Needs updating for latest spec

### ISSUE THREAD

**Issue by rocketraman** [yosuke-furukawa/server-timing#13]
This needs updating for the latest spec. See examples here: https://w3c.github.io/server-timing/#examples

**Comment by yosuke-furukawa** [comment]
Are you saying about support `Trailer` header? if so, I will do it soon.

**Comment by rocketraman** [comment]
That too, but mainly the syntax for `dur`, names, and descriptions.

**Comment by yosuke-furukawa** [comment]
Is this similar to https://github.com/yosuke-furukawa/server-timing/pull/12 ?

**Comment by rocketraman** [comment]
@yosuke-furukawa Yes it is. I see that you merged the pull, thanks.
