### ISSUE TITLE
Same project

### ISSUE THREAD

**Issue by thomasbrueggemann** [yosuke-furukawa/server-timing#2]
Insane, we startet working on the same idea, at the same time! :D 

Here is my approach:
https://github.com/thomasbrueggemann/node-servertiming

**Comment by yosuke-furukawa** [comment]
Ya, it is similar :) 
However my module is to use server middleware like express-middleware.
But your idea `startTimer/endTimer` is good.

**Comment by thomasbrueggemann** [comment]
I like the middleware approach too.
A combination would be awesome :)
