### ISSUE TITLE
Question on the server timing on Chrome 58+

### ISSUE THREAD

**Issue by motss** [yosuke-furukawa/server-timing#9]
There's a huge difference between the implementation of the Server Timing on Chrome 57 and Chrome 58+. It seems like Chrome 57 treated it the timing in milliseconds while in microseconds in Chrome 58+.

Not sure which version has the correct implementation of Server Timing. Please advise if this is normal behavior or a bug.

Ran a test from the given example (see URL) and get different results:

## Server timing on Chrome 60
![server-timing-on-chrome-60](https://cloud.githubusercontent.com/assets/10607759/25237420/3771f6a2-261d-11e7-8f9d-2019c94af4c0.png)

## Server timing on Chrome 57
![server-timing-on-chrome-57](https://cloud.githubusercontent.com/assets/10607759/25237421/378534d8-261d-11e7-9c3a-fbf26d4f2960.png)

**Comment by lauterry** [comment]
Hi

See https://gist.github.com/paulirish/a76ac17fc211b019e538c09d8d827691 comment section

**Comment by motss** [comment]
@lauterry 
@yosuke-furukawa 

So previously was in **seconds (s)** and the latest one should be in **milliseconds (ms)**. So we should all change accordingly.

Timing used in the source code are all in **seconds (s)**:

* [index.js](https://github.com/yosuke-furukawa/server-timing/blob/master/index.js#L24)
* [timer.js](https://github.com/yosuke-furukawa/server-timing/blob/master/timer.js#L20)

```js
// Before (in seconds):
const duration = process.hrtime(timeObj.start);
const value = (duration[0] + duration[1] * 1e-9); // This will in seconds!

// After (in milliseconds):
const duration = process.hrtime(timeObj.start);
const value = (duration[0] + duration[1] * 1e-6); // This will in milliseconds!
```

**Comment by yosuke-furukawa** [comment]
ooops.

**Comment by motss** [comment]
@yosuke-furukawa 

I'm interested in submitting a PR to get that fixed on latest Chrome if the implementation shown above is correct based on my understanding.

WDYT?
